server:
 port: 8080
 servlet:
  context-path: /bootcamp
  
  
spring:
 datasource:
  url: postgres://xwdphikiorthau:26e4e99d77663b293dd508a34487becaa63d0f81ddca52ac91f536722d8ccd21@ec2-35-170-85-206.compute-1.amazonaws.com:5432/d738t1km5ob9do
  username: xwdphikiorthau
  password: 26e4e99d77663b293dd508a34487becaa63d0f81ddca52ac91f536722d8ccd21
  driver-class-name: org.postgresql.Driver
 jpa:
  show-sql: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  generate-ddl: true
  hibernate:
    ddl-auto: none
      
application:
 description: Projeto criado para o bootcamp DIO - Santander
 version: 1.0